import type {ResearchState} from './research.ts';
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const names={discovery:'Открытия',skill:'Навыки и опыт',decision:'Мои решения',astrology:'Астрологические сопоставления'};
export function atlasCollections(s:ResearchState){
 const entries=s.atlas??[],draft=s.drafts.atlas??{},trials=s.answers.filter(a=>a.source==='SELF_REPORTED_ACTION');
 const cards=Object.entries(names).map(([kind,name])=>{const rows=entries.filter(e=>e.kind===kind);return `<details class="collection" ${kind==='discovery'?'open':''}><summary><span class="collection-star" aria-hidden="true">✧</span> ${name} <small>${rows.length} записей</small></summary>${kind==='astrology'?'<p>Твоя ручная проверка трактовки или прогноза. Укажи исходный текст, дату и событие. Совпадение не доказывает причинную связь.</p>':kind==='skill'?'<p>Практика и твои впечатления. Баллы способностей и уровень мастерства автоматически не назначаются.</p>':''}${rows.map(e=>{const a=s.answers.find(a=>a.id===e.evidenceId);return `<article class="atlas-record"><p class="atlas-source">Твоя запись · ${esc(e.recordedAt.slice(0,10))} · версия ${e.revision}</p><p class="atlas-note">${esc(e.text)}</p><strong>${esc(e.status)}</strong>${a?`<p>Основание: <a href="#research/${esc(a.day)}">${esc(a.day)} · ${esc(a.choices.join(', '))}</a>${a.revision!==e.evidenceRevision?' · Основание изменено — пересмотри вывод.':''}</p>`:'<p>Личная заметка без привязанного наблюдения.</p>'}<button class="text-button" data-research="atlas-edit:${esc(e.id)}">Уточнить запись</button></article>`;}).join('')||'<p>Коллекция пока пуста. Добавь то, что считаешь важным для себя.</p>'}</details>`;}).join('');
 const months=[...new Set([...s.answers.map(a=>a.day.slice(0,7)),...entries.map(e=>e.recordedAt.slice(0,7))])].sort().reverse();
 return `<section class="personal-atlas"><p class="lead">Твоя обсерватория наполняется опытом.</p><div class="atlas-compass"><span>Что я узнал</span><span>Что мне подошло</span><span>Что проверю дальше</span></div><p>Сохраняй собственные открытия, возвращайся к основаниям и меняй мнение, когда появляется новый опыт.</p>${cards}
 <details class="collection"><summary>✧ Пробы · ${trials.length} отметок о действии</summary>${trials.map(a=>`<article class="atlas-record"><a href="#research/${esc(a.day)}">${esc(a.day)} · ${esc(a.choices.join(', '))}</a><p>${esc(a.prompt)}</p><p>${esc(a.note)}</p></article>`).join('')||'<p>Здесь появятся твои отметки о выполненных и частичных пробах.</p>'}<a class="text-button" href="#journal">Все исходы, включая пропуски →</a></details>
 <details class="collection"><summary>✧ История исследования · ${months.length} месяцев с записями</summary>${months.map(m=>`<article class="atlas-record"><h4>${esc(m)}</h4><p>${s.answers.filter(a=>a.day.startsWith(m)).length} записей по дням · ${entries.filter(e=>e.recordedAt.startsWith(m)).length} записей в коллекциях</p></article>`).join('')||'<p>История начнётся с первой записи. Перерыв ничего не обнуляет.</p>'}<p>Прошедший месяц сам по себе не подтверждает вывод. Открытые вопросы остаются открытыми.</p>${(s.atlasHistory??[]).length?`<details><summary>Предыдущие версии · ${s.atlasHistory!.length}</summary>${s.atlasHistory!.map(e=>`<p>${esc(e.recordedAt.slice(0,10))} · версия ${e.revision}: ${esc(e.text)} — ${esc(e.status)}</p>`).join('')}</details>`:''}</details>
 <details class="atlas-editor" ${draft.id?'open':''}><summary>${draft.id?'Уточнить запись':'Добавить в свою коллекцию'}</summary><form id="research-atlas" data-research-form="atlas"><input type="hidden" name="id" value="${esc(draft.id)}"><label>Коллекция<select name="kind">${Object.entries(names).map(([k,n])=>`<option value="${k}" ${draft.kind===k?'selected':''}>${n}</option>`).join('')}</select></label><label>Что ты хочешь сохранить?<textarea name="text" maxlength="1000" required>${esc(draft.text)}</textarea></label><label>На какой записи это основано?<select name="evidenceId"><option value="">Личная заметка без основания</option>${s.answers.map(a=>`<option value="${esc(a.id)}" ${draft.evidenceId===a.id?'selected':''}>${esc(a.day)} · ${esc(a.choices.join(', '))}</option>`).join('')}</select></label><label>Твоя оценка<select name="status">${['Исследую','Хочу продолжить','Отложено','Не подходит','Совпало','Частично','Не совпало','Недостаточно информации'].map(v=>`<option ${draft.status===v?'selected':''}>${v}</option>`).join('')}</select></label><button class="primary wide" type="submit">Сохранить в обсерватории</button></form></details></section>`;
}
