import type { Expedition } from './expedition';
import { calendar,dayNumber,weeklyReports,horizon,encounterFor } from './expedition';
import type { Journey } from './journey';
import { PLANETS } from './journey';
import { DAYS,isStale } from '../domain';
export const escapeHtml=(v:unknown)=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const esc=escapeHtml;
export function routeBody(e:Expedition,j:Journey,today:string){
 const d=dayNumber(e,today),rows=calendar(e,j,today),recorded=rows.filter(r=>['done','partial','skipped'].includes(r.state)).length;
 return `<p class="lead">${esc(j.data.goal.title)}</p><div class="expedition-stats"><strong>${Math.min(d,30)}<small> / 30 дней</small></strong><span>${recorded} дней с отметками<br>не число выполненных действий</span></div><p>Один посильный шаг в выбранный день. Встречи в пути помогают заметить опыт, а новые миры — увидеть этапы.</p><div class="expedition-calendar" aria-label="Календарь 30 дней">${rows.map(r=>`<button data-day="${r.date}" class="day-cell ${r.state} ${r.current?'current':''}" ${r.date>today?'disabled':''} aria-label="День ${r.day}, ${r.date}: ${{done:'сделано',partial:'частично',skipped:'пропуск',future:'впереди',rest:'свободный день',unrecorded:'нет записи'}[r.state]}">${r.day}</button>`).join('')}</div><p class="small-note">● Сделано · ◐ Частично · — Пропуск. Пустой день — не неудача. Прошедшие дни без записи не заполняются автоматически.</p><button class="primary wide" data-action="daily">${d>30?'Продолжить после экспедиции':'К сегодняшней пробе'} ↗</button><button class="text-button wide" data-action="encounter">Встреча с помощником</button><div class="checkpoint">${PLANETS.slice(0,5).map((p,i)=>`<button data-planet="${p.id}">${i<=j.stage?'◉':'○'} ${p.name} — ${p.subtitle}</button>`).join('')}</div><h3>Промежуточные итоги</h3>${weeklyReports(e,j,today).map(w=>`<article class="journal-item"><span>${w.from} — ${w.to}</span><p>${w.completed} сделано · ${w.partial} частично · ${w.skipped} пропусков<br>${w.minutes} минут${w.unknownMinutes?' + есть неизвестное время':''}. Дней без отметки: ${w.missing} из ${w.days} календарных.</p></article>`).join('')}<button class="ghost wide" data-action="compare-plans">Сравнить маршруты на 90 дней</button><p class="small-note">Доступные миры — этапы знакомства с маршрутом, не доказательство завершения 30 дней или достижения цели.</p>`;
}
export function contextBody(e:Expedition){
 const fields=[['why','Зачем мне это сейчас','Что хочется изменить?'],['support','Поддерживающее направление','Например: чтение или спокойный ритм'],['experiment','Экспериментальный интерес','Что хочется попробовать без обязательств'],['resources','Что уже есть','Навыки, материалы, поддержка'],['barrier','Что стоит учитывать','Время, неопределённость, усталость'],['retrospective','Что помню о предыдущем месяце','Необязательный контекст, не доказательство прогноза']] as const;
 return `<p class="lead">У тебя может быть несколько интересов. Основную цель выбираешь ты; остальные не обязаны исчезать.</p><form id="context-form">${fields.map(([key,label,placeholder])=>`<label>${label}<textarea name="${key}" maxlength="500" placeholder="${placeholder}">${esc(e.context[key])}</textarea></label>`).join('')}<p class="small-note">Любое поле можно оставить пустым. Воспоминания не добавляются в календарь выполненных проб.</p><button class="primary wide" type="submit">Сохранить контекст ↗</button></form>`;
}
export function companionBody(e:Expedition,j:Journey,today:string){
 const card=encounterFor(e,today),old=e.encounters.find(a=>a.day===today&&a.id===card.id);
 return `<div class="encounter-emblem" aria-hidden="true">✧</div><p class="eyebrow">${esc(card.name)}</p><p class="lead">${esc(card.title)}</p><form id="encounter-form"><fieldset><legend>Выбери ответ</legend><div class="encounter-choices">${card.choices.map(c=>`<label class="choice"><input type="radio" name="choice" value="${esc(c)}" ${old?.choice===c?'checked':''} required> ${esc(c)}</label>`).join('')}</div></fieldset><label>Моё дополнение — необязательно<textarea name="note" maxlength="500">${esc(old?.note??'')}</textarea></label><button type="submit" class="primary wide">Ответить навигатору ↗</button></form>${old?`<blockquote>${esc(card.reply)}</blockquote>`:''}<p class="small-note">Ответ — твои слова, не диагноз и не выполненное действие. ${j.data.observations.length?'В журнале есть пробы — их можно обсудить без оценки личности.':'Опыта пока мало; не будем делать выводы заранее.'}</p><button class="text-button" data-action="daily">К посильному действию</button>`;
}
export function horizonBody(e:Expedition,j:Journey,today:string){
 const h=horizon(e,j,today),p=h.plan;
 return `<h3>Три возможных решения</h3><ul>${h.alternatives.map(t=>`<li>${t}</li>`).join('')}</ul><p>Варианты ниже различаются темпом, не оценкой способностей. Для смены цели вернись на Исток.</p>${p?`<h3>Подтверждённый тобой ближайший этап</h3><p>${p.totalMinutes} минут в неделю · ${p.cost} ₽. ${isStale(j.data)?'Данные изменились: нужен пересмотр.':'План соответствует текущей ревизии.'}</p><ol class="plan-list">${p.items.map(i=>`<li><span>${DAYS[i.day]} · ${i.time} · ${i.minutes} минут</span>${esc(i.title)}<small>${esc(i.result)}</small></li>`).join('')}</ol>`:''}<h3>Горизонт 90 дней</h3><div class="checkpoint">${h.checkpoints.map(c=>`<span>Через ${c.day} дней · ${c.date}<br>${c.question}</span>`).join('')}</div><p>Ближайший пересмотр: ${h.reviewOn}. При пропуске не удваивай нагрузку: продолжи в удобное окно, уменьши шаг или пересмотри цель.</p><details><summary>Почему предложен этот маршрут?</summary><p>Основания: выбранная цель, ${j.data.schedule.days.length} доступных дней в неделю по ${j.data.schedule.minutes} минут. ${h.summary.recorded} самоотчётов с ${e.start} по ${today}.</p><p>Неизвестно: устойчивость интереса и результат будущих действий. ${h.summary.skipped?'Есть пропуски — причину нельзя угадать по числу отметок.':''}${h.summary.completed&&h.summary.partial?' Опыт неоднороден: есть и завершённые, и частичные пробы.':''}</p><ul>${h.limits.map(t=>`<li>${t}</li>`).join('')}</ul><p>Контекст пользователя: ${esc(e.context.barrier||'Препятствия пока не указаны.')}</p></details>`;
}
