import type { ResearchState } from './research.ts';
import { exampleNatal,zodiac,SIGNS } from './natal.ts';
import { monthReady } from './month-review.ts';
const point=(a:number,r:number)=>[220-r*Math.cos(a*Math.PI/180),220+r*Math.sin(a*Math.PI/180)];
export function natalBody(s:ResearchState,today:string){
 if(!s.birth)return '<p>Сначала укажи данные рождения.</p><a href="#birth">Заполнить данные</a>';
 if(!monthReady(s,today))return '<h3>Карта откроется после первого месяца</h3><p>Сначала собираем собственные наблюдения, затем смотрим символическую интерпретацию. Пропущенный день не начинает отсчёт заново.</p><a class="text-button" href="#journal">Мои записи</a>';
 const n=exampleNatal(s.birth);
 if(!n)return '<h3>Для этой записи нужен расчёт</h3><p>Автоматический выбор координат и исторического часового пояса для произвольного места ещё не подключён. Карта не будет подменена картой примера. Сейчас проверен расчёт для исходных данных аккаунта 1.</p><a href="#birth">Проверить данные рождения</a>';
 const pos=(lon:number,r:number)=>point(lon-n.asc,r),glyph=['☉','☽','☿','♀','♂','♃','♄','♅','♆','♇'];
 const svg=`<svg class="natal-wheel" viewBox="0 0 440 440" role="img" aria-label="Натальная карта: тропический зодиак, равные дома. Точные значения в таблице ниже."><circle cx="220" cy="220" r="204"/><circle cx="220" cy="220" r="173"/><circle cx="220" cy="220" r="126"/>${SIGNS.map((name,i)=>{const a=pos(i*30,173),b=pos(i*30,204),p=pos(i*30+15,189);return `<path d="M${a.join(' ')} L${b.join(' ')}"/><text x="${p[0]}" y="${p[1]}" class="natal-sign">${name}</text>`;}).join('')}${n.houses.map((lon,i)=>{const a=pos(lon,64),b=pos(lon,170),p=pos(lon+15,102);return `<path d="M${a.join(' ')} L${b.join(' ')}" class="natal-house"/><text x="${p[0]}" y="${p[1]}">${i+1}</text>`;}).join('')}${n.aspects.map(a=>{const x=pos(n.planets.find(p=>p.name===a.a)!.longitude,125),y=pos(n.planets.find(p=>p.name===a.b)!.longitude,125);return `<path class="natal-aspect" d="M${x.join(' ')} L${y.join(' ')}"/>`;}).join('')}${n.planets.map((p,i)=>{const xy=pos(p.longitude,136+(i%3)*11);return `<text class="natal-planet" x="${xy[0]}" y="${xy[1]}">${glyph[i]}</text>`;}).join('')}<text x="28" y="220">ASC</text></svg>`;
 return `<h3>Натальная карта</h3><p>14 мая 1992 · 09:30 · Казань. Историческое время UTC+4; момент расчёта 05:30 UTC.</p>${svg}<p>Асцендент: <strong>${zodiac(n.asc)}</strong>. Тропический зодиак; равнодомная система от ASC, не Плацидус.</p><div class="journal-table-wrap"><table class="journal-table"><caption>Рассчитанные положения</caption><thead><tr><th>Объект</th><th>Знак и градус</th><th>Дом</th></tr></thead><tbody>${n.planets.map(p=>`<tr><td>${p.name}${p.retrograde?' · R':''}</td><td>${zodiac(p.longitude)}</td><td>${p.house}</td></tr>`).join('')}</tbody></table></div><p class="small-note">R — ретроградное движение. Координаты центра Казани: 55.7961° N, 49.1064° E. Расчёт Astronomy Engine 2.1.19 выполняется здесь, без отправки анкеты.</p><details><summary>Аспекты и границы расчёта</summary><p>Основные углы 0°, 60°, 90°, 120°, 180°; единый орбис 6°. Узлы, Лилит и астероиды не рассчитываются.</p>${n.aspects.map(a=>`<p>${a.a} — ${a.b}: ${a.name}, отклонение ${a.orb.toFixed(2)}°.</p>`).join('')}</details><details><summary>Как читать, не подгоняя опыт</summary><p>Положения и углы рассчитаны астрономически. Их психологический смысл не следует из расчёта. Персональная астрологическая трактовка пока не подключена; здесь нет сгенерированного «портрета», замаскированного под результат.</p><p>Можно отдельно записать, что кажется подходящим, что не подходит и что слишком общее. Месячные наблюдения не меняются после открытия карты.</p></details>`;
}
