import type { Expedition } from './expedition';
import { addDays } from './expedition';
import type { Journey } from './journey';
import { DAYS } from '../domain';
import { NAVIGATOR_STEPS,buildNavigatorReport,navigatorStatus } from './navigator';
import { escapeHtml as esc } from './expedition-ui';

export function expeditionMap(e:Expedition,j:Journey,today:string){
  const status=navigatorStatus(e,j,today);
  return `<div class="program-caption"><span>ТВОЙ МАРШРУТ В ASTRA</span><span>День ${status.day} · ${status.summary.recorded} отметок</span></div><ol class="program-map" aria-label="Пять смыслов экспедиции">${NAVIGATOR_STEPS.map((s,i)=>`<li><button data-action="${s.action}" class="program-step planet-${s.id}"><span class="program-orb" aria-hidden="true">${i+1}</span><span><small>${s.planet} · ${s.period}</small><strong>${s.title}</strong><em>${s.text}</em></span></button></li>`).join('')}</ol><p class="small-note">Это схема работы, не оценка личности. Открытые экраны и полёт камеры не означают, что цель достигнута или 30 дней уже пройдены.</p>`;
}

export function rolesMap(e:Expedition,j:Journey){return `<section class="roles-map" aria-label="Три роли интересов"><div class="role-main"><span>ОСНОВНОЕ</span><strong>${esc(j.data.goal.title)}</strong><small>Сейчас пробуем это</small></div><div><span>ПОДДЕРЖИВАЮЩЕЕ</span><strong>${esc(e.context.support||'Можно не выбирать')}</strong><small>Помогает сохранять ресурс</small></div><div><span>ЭКСПЕРИМЕНТАЛЬНОЕ</span><strong>${esc(e.context.experiment||'Место для любопытства')}</strong><small>Без обязательства продолжать</small></div></section>`;}

export function guideBody(e:Expedition,j:Journey,today:string){return `<p class="lead">Не найти «единственное предназначение», а понять через опыт, что тебе подходит сейчас — и что делать дальше.</p><div class="program-promise"><div><b>30</b><span>дней коротких вопросов,<br>реальных проб и наблюдений</span></div><span aria-hidden="true">→</span><div><b>90</b><span>дней гибкого плана,<br>который выбираешь ты</span></div></div>${expeditionMap(e,j,today)}<h3>Каждый день — не ещё одна большая анкета</h3><ol class="daily-loop"><li><b>1</b><span>Короткий вопрос<small>В приложении · около минуты, без таймера</small></span></li><li><b>2</b><span>Одно реальное действие<small>Вне сайта · по доступному времени</small></span></li><li><b>3</b><span>Отметка и наблюдение<small>Сделал, частично или пропустил — любой ответ полезен</small></span></li></ol><div class="program-note"><strong>Польза — до конца месяца</strong><p>Сначала проясняем ограничения, затем появляются первые пробы и недельные итоги. Итог — инструкция действий, а не характеристика личности.</p></div><h3>Ты больше одной роли</h3>${rolesMap(e,j)}<p>Главное, поддерживающее и экспериментальное направления выбираешь ты. Мы не выводим профессию, талант или судьбу из игры.</p><details><summary>Астрология, игры и помощник — где границы?</summary><p>Астрология остаётся отдельным добровольным символическим слоем и не влияет на цели, нагрузку или практический план. Когнитивные игры помогают наблюдать выбор в конкретной ситуации, но не дают оценки IQ или профессиональной пригодности. Итоговое решение всегда остаётся за тобой.</p></details><button class="primary wide" data-action="${j.stage===0?'edit-goal':'start'}">${j.stage===0?'Выбрать цель и ритм':'К моему сегодняшнему шагу'} ↗</button>`;}

export function todayBody(e:Expedition,j:Journey,today:string){
  const s=navigatorStatus(e,j,today),attempts=s.summary.completed+s.summary.partial;
  return `<div class="program-caption"><span>${today}</span><span>ДЕНЬ ${s.day} ЭКСПЕДИЦИИ</span></div><p class="lead">${esc(j.data.goal.title)}</p><article class="next-action"><span class="eyebrow">ОДИН СЛЕДУЮЩИЙ ШАГ</span><h3>${esc(s.row?'На сегодня отметка уже есть':j.stage===0?'Сначала — твоя точка старта':s.mission.planned||j.demo?s.mission.title:'День без обязательной пробы')}</h3><p>${esc(s.reason)}</p>${!s.row&&j.stage>0&&(s.mission.planned||j.demo)?`<p>${esc(s.mission.result)}</p><div class="time-split"><span><b>≈1 мин</b> вопрос в приложении</span><span><b>${Math.min(j.data.schedule.minutes,15)} мин</b> реальное действие</span></div>`:''}<button class="primary wide" data-action="${s.action}">${s.label} ↗</button></article><div class="navigator-stats"><div><b>${attempts}</b><span>полных и частичных проб</span></div><div><b>${s.summary.recorded}</b><span>дней с отметками</span></div><div><b>${s.summary.minutes}</b><span>записанных минут${s.summary.unknownMinutes?' + неизвестное время':''}</span></div></div><p class="small-note">Период ${s.period.from} — ${s.period.to}. Пропуски и отсутствие записи не выдаём за выполненные действия.</p><div class="secondary-actions"><button class="choice" data-action="encounter">Встреча с Лирой</button><button class="choice" data-action="route">Моя карта 30 дней</button><button class="choice" data-action="guide">Как всё работает</button></div>${s.row?`<button class="text-button" data-action="edit-observation" data-observation="${esc(s.row.id)}">Исправить сегодняшнюю отметку</button>`:''}<details><summary>План на сегодня можно уменьшить или отложить</summary><p>Не догоняй двойной нагрузкой. Минимальная версия доступна в карточке действия. Смена цели и графика не стирает накопленные наблюдения.</p><button class="text-button" data-action="edit-goal">Изменить цель или время</button></details>`;
}

export function memoriesBody(e:Expedition){return `<p class="lead">Предыдущие четыре недели — необязательная точка опоры. Можно не помнить даты и пропустить весь раздел.</p><p>Вспомни занятия, ситуации, ограничения или моменты интереса. Это воспоминания, а не доказательство будущего результата.</p><form id="memory-form">${Array.from({length:4},(_,week)=>{
  const row=e.memoryDraft?.find(r=>r.week===week)??e.memoryWeeks?.find(r=>r.week===week);
  return `<fieldset class="memory-week"><legend>${addDays(e.start,-28+week*7)} — ${addDays(e.start,-22+week*7)}</legend><label>Что запомнилось?<textarea name="note-${week}" maxlength="500" placeholder="Можно оставить пустым">${esc(row?.note??'')}</textarea></label><label>Насколько уверенно помню<select name="confidence-${week}">${[['unknown','Не помню / не знаю'],['approximate','Примерно'],['sure','Уверенно']].map(([value,label])=>`<option value="${value}" ${row?.confidence===value||(!row&&value==='unknown')?'selected':''}>${label}</option>`).join('')}</select></label></fieldset>`;
}).join('')}<p class="small-note">Дата ввода хранится отдельно. Пустые поля не превращаются в события; воспоминания не заполняют календарь 30 дней.</p><button class="primary wide" type="submit">Сохранить воспоминания отдельно</button><button class="text-button" type="button" data-action="start">Пропустить и продолжить</button></form>`;}

export function evidenceBody(e:Expedition,j:Journey,today:string){
  const r=buildNavigatorReport(e,j,today),sum=r.summary;
  const counts=[['Сделано',sum.completed,'done'],['Частично',sum.partial,'partial'],['Пропущено',sum.skipped,'skipped'],['Нет отметки',sum.missing,'missing']] as const;
  return `<h3>Откуда берутся выводы</h3><div class="evidence-sources"><div><span>ТВОИ СЛОВА</span><b>${e.encounters.length}</b><small>ответов спутнику · не действия</small></div><div><span>ПРОБЫ</span><b>${sum.recorded}</b><small>самоотчётов за ${sum.days} календарных дней</small></div><div><span>ПРОШЛОЕ</span><b>${(e.memoryWeeks??[]).filter(w=>w.note).length}</b><small>воспоминаний · отдельно</small></div></div><div class="evidence-bars" aria-label="Сводка отметок за календарный период">${counts.map(([label,n,state])=>`<div class="evidence-row"><span>${label}</span><div><i class="${state}" style="width:${sum.days?n/sum.days*100:0}%"></i></div><b>${n}</b></div>`).join('')}</div><p class="small-note">${r.period.from} — ${r.period.to}. ${sum.missing} из ${sum.days} календарных дней без записи, включая дни отдыха. Это не число неудач. ${sum.unknownMinutes?'Есть отметки с неизвестным временем.':''}</p><details><summary>Что пока неизвестно и где есть противоречия?</summary><ul>${[...r.contradictions,...r.unknowns].map(x=>`<li>${esc(x)}</li>`).join('')}</ul><p>Рекомендации опираются на отмеченные ответы и действия. Это проверяемые предложения, а не измерение личности.</p></details>`;
}

export function passportBody(e:Expedition,j:Journey,today:string){
  const r=buildNavigatorReport(e,j,today);
  return `<p class="eyebrow">${r.status==='approved'?'ВЫБРАНО ТОБОЙ':r.status==='needs-review'?'ТРЕБУЕТ ПЕРЕСМОТРА':'ЧЕРНОВИК · ПЛАН ЕЩЁ НЕ ВЫБРАН'}</p><p class="lead">${esc(r.goal.title)}</p><div class="program-note"><span class="eyebrow">КАК ПОЙМУ, ЧТО ПРОДВИНУЛСЯ</span><p>${esc(r.criterion)}</p></div>${rolesMap(e,j)}<dl class="route-facts"><dt>Зачем мне это</dt><dd>${esc(r.why)}</dd><dt>Ресурсы</dt><dd>${esc(r.resources??'Пока не указаны — не считаем их безграничными.')}</dd><dt>Ограничения</dt><dd>${esc(r.barriers??'Пока не указаны — можно дополнить на Истоке.')}</dd></dl><h3>Какие варианты есть</h3><div class="route-alternatives">${r.alternatives.map(a=>`<article><strong>${a.title}</strong><p>${a.benefit}</p><small>${a.tradeoff}</small></article>`).join('')}</div>${r.status==='needs-review'?'<p class="warning">Исходные записи изменились. Ниже сохранён прежний план; он не обновлён молча.</p>':''}<h3>Ближайшая неделя</h3>${r.nextWeek.length?`<p>${r.weeklyMinutes} минут · ${r.budget} ₽ плановых расходов. Это лимит плана, не расчёт твоих доходов.</p><ol class="plan-list">${r.nextWeek.map(i=>`<li><span>${DAYS[i.day]} · ${i.time} · ${i.minutes} минут</span>${esc(i.title)}<small>Результат: ${esc(i.result)}</small></li>`).join('')}</ol>`:'<p>После первой пробы и наблюдения сравним посильные варианты. Заполненного плана пока нет.</p>'}<h3>Гибкий горизонт, а не 90 жёстких заданий</h3><ol class="horizon-line">${r.checkpoints.map(c=>`<li><b>${c.day}</b><span>${c.date}<small>${c.question}</small></span></li>`).join('')}</ol><p>Ближайший пересмотр: ${r.reviewOn}.</p><div class="program-note"><strong>Если пропустил</strong><p>${r.recovery}</p></div>${evidenceBody(e,j,today)}<details><summary>Исходные записи, на которых стоит сводка</summary>${r.evidence.length?r.evidence.map(o=>`<p>${o.date} · ${esc(o.id)} · ревизия ${o.revision}<br>${esc(o.note||'Без дополнения')}<br><small>Источник: самоотчёт пользователя, не независимая проверка.</small></p>`).join(''):'<p>Проб пока нет. Не делаем вид, что основания уже собраны.</p>'}<p>${esc(r.sourceLabel)}</p></details><div class="secondary-actions"><button class="primary" data-action="compare-plans">${r.status==='approved'?'Пересмотреть выбор':'Выбрать маршрут'}</button><button class="choice" data-action="context">Уточнить ресурсы</button><button class="choice" data-action="discoveries">Исправить исходные записи</button><button class="choice" data-action="export">Скачать инструкцию и данные</button></div><p class="small-note">Экран и экспорт используют один объект отчёта. Астрология и когнитивные игры не определяют твои цели и способности.</p>`;
}
