import {pc} from './playcanvas-runtime.js';
import {WORLDS,flightPose,flightWorld,FLIGHT_STOPS,OBSERVATORY_POSITION,OBSERVATORY_ROTATION} from './playcanvas-path.js';
import {WORLD_THEMES} from './world-themes.ts';
import {PLANETS} from './journey.ts';
import {preloadPlanetPreviews} from './planet-preload.js';
import {applyPlanetFinish} from './playcanvas-materials.js';
import {createObservatoryMirror} from './playcanvas-mirror.js';
import {addEnergyRing} from './playcanvas-energy.js';
import {addOriginInscription} from './playcanvas-inscription.js';
import {planetHazeParticles} from './playcanvas-haze.js';
import {applyCoastMaterials} from './playcanvas-coast.js';
import {asteroidPoint,asteroidPointAt,arcParameter,ASTEROID_LENGTH,asteroidMistDensity,serpentSpiralPose,SERPENT_SPIRALS,STORM_CLUSTERS,MIST_SHAPES,createFlashSchedule} from './playcanvas-weather.js';
import {addVolumes} from '../../prototypes/galaxy-playcanvas/volumes.js';
import modelUrl from '../../prototypes/observatory-blender/assets/observatory.glb?url';
import architectureUrl from '../../prototypes/observatory-blender/assets/architecture-reference-v2.png?url';

// Rendering, textures, entities, input and route mathematics belong to PlayCanvas.
export function createGalaxyScene(host,labelHost,callbacks){
 const canvas=document.createElement('canvas');canvas.tabIndex=0;canvas.setAttribute('aria-label','Вселенная ASTRA. Колесо и свайп — полёт, нажатие на планету — открыть её.');host.append(canvas);
 const reduced=matchMedia('(prefers-reduced-motion: reduce)');
 let paused=reduced.matches,disposed=false,stage=0,mode='flight',app,device,camera,frame,station,fog,energy,mirror,effectsLayer,coast,coastPromise,observatoryPromise;
 let elapsed=0,travel=0,desiredTravel=0,yaw=0,pitch=0,flightYaw=0,press=null,transition,landed=false;
 let desiredPosition=new pc.Vec3(-1,5,18),desiredTarget=new pc.Vec3(-7,5,-13),target=desiredTarget.clone();
 const worlds=[],labels=[],assets=[],cleanup=[],mists=[];const stats={fps:0,calls:0,triangles:0,surface:false};
 try{paused=paused||sessionStorage.getItem('astra.motion-paused')==='true';}catch{}
 host.dataset.engine='playcanvas';host.dataset.observatory='loading';
 const vec=value=>new pc.Vec3(...value),position=value=>new pc.Vec3(value.x,value.y,value.z);
 const rgb=hex=>new pc.Color(((hex>>16)&255)/255,((hex>>8)&255)/255,(hex&255)/255);
 function material(color,metal=.2,gloss=.7,emission=0){const m=new pc.StandardMaterial();m.diffuse=rgb(color);m.useMetalness=true;m.metalness=metal;m.gloss=gloss;if(emission){m.emissive=rgb(emission);m.emissiveIntensity=2.4;}m.update();return m;}
 function mesh(name,geometry,mat,parent=app.root){const e=new pc.Entity(name);e.addComponent('render',{meshInstances:[new pc.MeshInstance(pc.Mesh.fromGeometry(device,geometry),mat)]});parent.addChild(e);return e;}
 function load(name,type,url){return new Promise((resolve,reject)=>{const a=new pc.Asset(name,type,{url});assets.push(a);app.assets.add(a);a.ready(()=>{if(disposed){a.unload();reject(new Error('Scene disposed'));}else resolve(a);});a.once('error',reject);app.assets.load(a);});}
 function on(element,event,handler,options){element.addEventListener(event,handler,options);cleanup.push(()=>element.removeEventListener(event,handler,options));}
 function setModeValue(next){mode=next;host.dataset.cameraMode=next;document.body.dataset.cameraMode=next;landed=false;callbacks.landed(false);yaw=pitch=flightYaw=0;if(coast)coast.enabled=next==='surface';}
 function fly(pos,look,duration=1.6){desiredPosition=pos;desiredTarget=look;transition=paused||reduced.matches?0:duration;}
 function home(forceFlight=false){if(stage===4&&!forceFlight){overview();return;}setModeValue('flight');travel=desiredTravel=FLIGHT_STOPS[Math.min(stage,4)];const pose=flightPose(travel);fly(position(pose.position),position(pose.target));}
 function overview(){setModeValue('map');fly(new pc.Vec3(innerWidth<700?100:74,72,innerWidth<700?128:48),new pc.Vec3(-10,0,-66),2.3);}
 function present(){setModeValue('focus');fly(new pc.Vec3(-1,4,19),new pc.Vec3(4,4,-25),1.4);}
 function focus(id){if(id==='about'){land();return;}const spec=WORLDS[id];if(!spec)return;setModeValue('focus');const p=vec(spec.position);fly(p.clone().add(new pc.Vec3(spec.radius*.9,spec.radius*.65,spec.radius*(innerWidth<700?6.4:3.7))),p);}
 function observatory(){setModeValue('observatory');void loadObservatory();const p=vec(OBSERVATORY_POSITION);fly(p.clone().add(new pc.Vec3(innerWidth<700?54:23.4,1.35,0)),p.clone().add(new pc.Vec3(0,5.76,0)));}
 async function land(){setModeValue('surface');host.dataset.landscape='loading';try{if(!app)await ready;if(disposed||mode!=='surface')return;coastPromise??=Promise.all([load('Istok coast','container','/benchmark-origin/coast.glb'),load('coast stone','texture','/benchmark-origin/stone.webp')]).then(([a,stone])=>{coast=a.resource.instantiateRenderEntity();coast.setLocalScale(.22,.22,.22);coast.setPosition(-8,5.64,0);app.root.addChild(coast);stone.resource.anisotropy=device.maxAnisotropy;applyCoastMaterials(pc,coast,stone.resource);const inscription=addOriginInscription(pc,device,coast);cleanup.push(()=>inscription.destroy());return coast;});await coastPromise;if(disposed||mode!=='surface')return;coast.enabled=true;host.dataset.landscape='ready';fly(new pc.Vec3(innerWidth<700?-8:-7.94,5.98,innerWidth<700?1.1:.88),new pc.Vec3(-8,5.88,-.198),2.2);}catch(error){coastPromise=null;host.dataset.landscape='failed';console.error(error);}}
 function scrub(value){if(!Number.isFinite(value))return;if(mode!=='flight')setModeValue('flight');transition=undefined;desiredTravel=value;}
 async function loadObservatory(){if(!app){await ready;if(disposed)return;}if(observatoryPromise)return observatoryPromise;observatoryPromise=(async()=>{
  const [model,reference]=await Promise.all([load('approved observatory','container',modelUrl),load('architecture reference','texture',architectureUrl)]);if(disposed)return;
  station=new pc.Entity('ASTRA observatory');station.setPosition(...OBSERVATORY_POSITION);station.setLocalScale(.6,.6,.6);station.setEulerAngles(0,OBSERVATORY_ROTATION*180/Math.PI,0);app.root.addChild(station);
  reference.resource.anisotropy=device.maxAnisotropy;
  const building=model.resource.instantiateRenderEntity();station.addChild(building);const inverse=new pc.Mat4().copy(station.getWorldTransform()).invert();
  for(const render of building.findComponents('render'))for(const mi of render.meshInstances){if(['Ice','IcePale','Titanium','Glazing'].includes(mi.material.name))mi.material=boundedReferenceMaterial(reference.resource,inverse,mi.material);else{const m=mi.material.clone();m.useMetalness=true;m.metalness=.85;m.gloss=.8;m.update();mi.material=m;}}
  const red=material(0xff2544,0,.5,0xff1538),green=material(0x36ffad,0,.5,0x27ff9a);
  for(const r of [9.30,9.42]){const ring=mesh('energy ring',new pc.TorusGeometry({ringRadius:r,tubeRadius:.023,segments:192,sides:5}),red,station);ring.setLocalPosition(0,11.5,-5.3);ring.setLocalEulerAngles(90,0,0);}
  const beam=mesh('green energy beam',new pc.CylinderGeometry({radius:.038,height:38,capSegments:10}),green,station);beam.setLocalPosition(0,23,-.8);energy=addEnergyRing(pc,device,station,effectsLayer.id);fog=addVolumes(pc,device,station,camera,{layer:effectsLayer.id,omitFoundation:true});mirror=createObservatoryMirror(pc,app,device,station,camera,effectsLayer);
  const button=document.createElement('button');button.className='planet-label observatory-label';button.textContent='Обсерватория';button.setAttribute('aria-label','Открыть обсерваторию');button.addEventListener('click',callbacks.observatory);labelHost.append(button);labels.push({button,entity:station,offset:12.7});host.dataset.observatory='ready';
 })().catch(error=>{host.dataset.observatory='failed';console.error(error);});return observatoryPromise;}
 function referenceMaterial(texture,inverse,glass){const m=new pc.ShaderMaterial({uniqueName:'astra-ref-'+glass,attributes:{aPosition:pc.SEMANTIC_POSITION,aNormal:pc.SEMANTIC_NORMAL},vertexGLSL:'attribute vec3 aPosition;attribute vec3 aNormal;uniform mat4 matrix_model;uniform mat4 matrix_viewProjection;uniform mat4 architectureSpace;varying vec3 p;void main(){vec4 w=matrix_model*vec4(aPosition,1.);p=(architectureSpace*w).xyz;gl_Position=matrix_viewProjection*w;}',fragmentGLSL:`uniform sampler2D referenceMap;varying vec3 p;void main(){vec2 uv=abs(p.x)>9.55?vec2((573.-abs(p.x)*26.0465116)/1092.,(575.-(p.y-.25)*26.0465116)/702.):vec2((573.+p.x*26.0465116)/1092.,(575.-(p.y-.25)*35.73)/702.);vec3 color=pow(texture2D(referenceMap,clamp(uv,vec2(.001),vec2(.999))).rgb,vec3(2.2));gl_FragColor=vec4(color,${glass?'.65':'1.'});}`});m.setParameter('referenceMap',texture);m.setParameter('architectureSpace',inverse.data);m.cull=pc.CULLFACE_NONE;if(glass){m.blendType=pc.BLEND_NORMAL;m.depthWrite=false;}return m;}
 function boundedReferenceMaterial(texture,inverse,original){
  const m=original.clone(),glass=original.name==='Glazing';
  m.shaderChunks.glsl.set('diffusePS',`uniform sampler2D architectureRef;uniform mat4 architectureSpace;
void getAlbedo(){vec3 p=(architectureSpace*vec4(vPositionW,1.)).xyz;vec2 uv;float mask;
${glass?`uv=vec2((573.+p.x*26.0465116)/1092.,(575.-(p.y-.25)*35.73)/702.);mask=step(.5,p.z)*(1.-step(4.2,p.z))*(1.-step(9.05,abs(p.x)))*step(.5,p.y);`:`uv=vec2((573.-abs(p.x)*26.0465116)/1092.,(575.-(p.y-.25)*26.0465116)/702.);mask=step(9.55,abs(p.x))*step(.27,p.y);`}
mask*=step(0.,uv.x)*step(uv.x,1.)*step(0.,uv.y)*step(uv.y,1.);vec3 reference=pow(texture2D(architectureRef,clamp(uv,vec2(.001),vec2(.999))).rgb,vec3(2.2));dAlbedo=mix(material_diffuse,reference*${glass?'1.16':'1.42'},mask*.8);}`);
  m.setParameter('architectureRef',texture);m.setParameter('architectureSpace',inverse.data);m.update();return m;
 }
 function createNebulae(){
  let seed=8714;const random=()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/4294967296);
  const quad=new pc.Mesh(device);quad.setPositions([-.5,-.5,0,.5,-.5,0,.5,.5,0,-.5,.5,0]);quad.setUvs(0,[0,0,1,0,1,1,0,1]);quad.setIndices([0,1,2,0,2,3]);quad.update();
  function puff(name,pos,size,color,opacity,storm=false){
   const mat=new pc.ShaderMaterial({uniqueName:'astra-soft-nebula',attributes:{aPosition:pc.SEMANTIC_POSITION,aUv:pc.SEMANTIC_TEXCOORD0},vertexGLSL:'attribute vec3 aPosition;attribute vec2 aUv;uniform mat4 matrix_model;uniform mat4 matrix_viewProjection;varying vec2 uv;void main(){uv=aUv;gl_Position=matrix_viewProjection*matrix_model*vec4(aPosition,1.);}',fragmentGLSL:`varying vec2 uv;uniform vec3 tint;uniform float opacity;uniform float time;uniform float phase;uniform float flash;
float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}
float noise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*f*(f*(f*6.-15.)+10.);return mix(mix(hash(i),hash(i+vec2(1,0)),f.x),mix(hash(i+vec2(0,1)),hash(i+vec2(1,1)),f.x),f.y);}
float cloud(vec2 p){float value=0.,weight=.52;mat2 rotation=mat2(.8,-.6,.6,.8);for(int i=0;i<5;i++){float footprint=max(length(dFdx(p)),length(dFdy(p)));value+=weight*mix(noise(p),.5,smoothstep(.25,1.,footprint));p=rotation*p*2.03+vec2(7.3,13.1);weight*=.48;}return value;}
void main(){vec2 p=(uv-.5)*2.;float edge=1.-smoothstep(.15,1.,length(p));vec2 drift=vec2(time*.025,phase);vec2 warp=vec2(cloud(p*2.+drift),cloud(p*2.+drift+19.7))-.5;float n=cloud(p*3.+warp*1.8+drift);float density=edge*edge*smoothstep(.20,.80,n);vec3 color=mix(tint,vec3(2.1,.025,.65),flash*.8);gl_FragColor=vec4(color,density*opacity*(1.+flash*.65));}`});
   mat.blendType=pc.BLEND_NORMAL;mat.depthWrite=false;mat.cull=pc.CULLFACE_NONE;mat.setParameter('tint',color);mat.setParameter('opacity',opacity);mat.setParameter('time',0);mat.setParameter('phase',random()*30);mat.setParameter('flash',0);
   const e=new pc.Entity(name);e.addComponent('render',{meshInstances:[new pc.MeshInstance(quad,mat)],layers:[effectsLayer.id]});app.root.addChild(e);e.setPosition(...pos);e.setLocalScale(size[0],size[1],1);const item={entity:e,material:mat,flash:storm,schedule:storm?createFlashSchedule(random,random()*3):null};mists.push(item);return item;
  }
  for(let i=0;i<24;i++)puff('space nebula',[(random()-.5)*170,(random()-.5)*90,-20-random()*240],[45+random()*65,25+random()*45],i%3===0?[.31,.10,.6]:i%3===1?[.025,.3,.45]:[.04,.08,.4],.32);
  worlds.forEach((w,index)=>{const center=vec(w.spec.position);for(const spec of planetHazeParticles(w.id,w.spec.radius,host.clientWidth<700,index*1.37)){const at=center.clone().add(spec.base),item=puff('planet mist',[at.x,at.y,at.z],[spec.width,spec.height],spec.color,spec.opacity*spec.form.density);item.haze={...spec,center,radius:w.spec.radius};}});
  const mobile=host.clientWidth<700,count=mobile?36:60,spacing=ASTEROID_LENGTH/(count-1),variation=i=>{const v=Math.sin(i*127.1+93.7)*43758.5453;return v-Math.floor(v);};
  for(let i=0;i<count;i++){const u=i/(count-1),at=asteroidPointAt(u),density=asteroidMistDensity(arcParameter(u));at.add(new pc.Vec3(Math.sin(i*2.7)*.65,Math.cos(i*1.9)*.55,Math.sin(i*1.1)*.7));const item=puff('pink-serpent-envelope',[at.x,at.y,at.z],[spacing*2.4+variation(i+81)*9+density*5,spacing*2.1+variation(i+190)*5],[.5,.055,.28],.13+density*.24);item.base=at;item.index=i;}
  SERPENT_SPIRALS.forEach((section,sectionIndex)=>{const n=mobile?18:28;for(let i=0;i<n;i++){const u=section.from+(section.to-section.from)*i/(n-1),pose=serpentSpiralPose(u),size=2.2+variation(i+sectionIndex*41)*1.8,item=puff('pink-serpent-spiral',[pose.position.x,pose.position.y,pose.position.z],[size*1.3,size],[.8,.12,.48],.32*pose.weight);item.coil={u,sectionIndex};item.material.blendType=pc.BLEND_ADDITIVEALPHA;}});
  STORM_CLUSTERS.forEach((t,i)=>{const at=asteroidPoint(t),[length,height,,restOpacity]=MIST_SHAPES[i];puff('steady-mist-glow',[at.x,at.y,at.z],[length,height],[.6,.07,.34],restOpacity);const item=puff('embedded-mist-flash',[at.x,at.y,at.z],[(10+i%3*2)*.95,(6+i%2*2)*.95],[1,.01,.15],1,true);item.material.blendType=pc.BLEND_ADDITIVEALPHA;item.schedule=createFlashSchedule(random,i*.37);item.entity.enabled=false;});host.dataset.asteroidWeather='pink-full-envelope-local-spirals-recurring-flashes';
 }
 const ready=(async()=>{
  device=await pc.createGraphicsDevice(canvas,{deviceTypes:[pc.DEVICETYPE_WEBGL2],antialias:true,powerPreference:'default'});if(disposed){device.destroy();return;}
  const options=new pc.AppOptions();options.graphicsDevice=device;options.componentSystems=[pc.RenderComponentSystem,pc.CameraComponentSystem,pc.LightComponentSystem];options.resourceHandlers=[pc.TextureHandler,pc.ContainerHandler];app=new pc.AppBase(canvas);app.init(options);app.setCanvasResolution(pc.RESOLUTION_AUTO);app.setCanvasFillMode(pc.FILLMODE_NONE);
  const resize=()=>{device.maxPixelRatio=Math.min(devicePixelRatio,host.clientWidth<700?1.3:1.6);app.resizeCanvas(host.clientWidth,host.clientHeight);canvas.style.width='100%';canvas.style.height='100%';host.dataset.pixelRatio=String(device.maxPixelRatio);};resize();const ro=new ResizeObserver(resize);ro.observe(host);cleanup.push(()=>ro.disconnect());
  effectsLayer=new pc.Layer({name:'ASTRA soft effects'});app.scene.layers.insertTransparent(effectsLayer,app.scene.layers.getOpaqueIndex(app.scene.layers.getLayerById(pc.LAYERID_IMMEDIATE)));
  camera=new pc.Entity('ASTRA camera');camera.addComponent('camera',{fov:innerWidth<700?56:48,nearClip:.025,farClip:1800,clearColor:new pc.Color(0,0,0)});camera.camera.layers=[...camera.camera.layers,effectsLayer.id];app.root.addChild(camera);camera.setPosition(desiredPosition);camera.lookAt(desiredTarget);
  app.scene.ambientLight=new pc.Color(.18,.22,.32);app.scene.exposure=1.05;frame=new pc.CameraFrame(app,camera.camera);frame.rendering.toneMapping=pc.TONEMAP_ACES;frame.bloom.intensity=.34;frame.bloom.threshold=.9;frame.bloom.blurLevel=5;frame.update();
  for(const [color,intensity,pos] of [[0xfff0d5,2.8,[-25,45,15]],[0x697bff,1.3,[30,10,-150]]]){const e=new pc.Entity('galaxy light');e.addComponent('light',{type:'directional',color:rgb(color),intensity,castShadows:false});app.root.addChild(e);e.setPosition(...pos);e.lookAt(0,0,-65);}
  for(const p of PLANETS.filter(p=>p.id!=='about')){const spec=WORLDS[p.id],theme=WORLD_THEMES[p.id];const mat=applyPlanetFinish(material(0xffffff,theme.metalness,1-theme.roughness),theme);const e=mesh(p.name,new pc.SphereGeometry({radius:spec.radius,latitudeBands:p.id==='origin'?256:96,longitudeBands:p.id==='origin'?384:144}),mat);e.setPosition(...spec.position);if(p.id==='origin')e.setEulerAngles(-40,-23,6);
   const button=document.createElement('button');button.className='planet-label';button.textContent=p.name;button.setAttribute('aria-label','Открыть планету '+p.name);button.addEventListener('click',()=>callbacks.pick(p.id));labelHost.append(button);labels.push({button,entity:e,offset:-spec.radius*1.12});worlds.push({id:p.id,entity:e,material:mat,spec,loaded:false});
  }
  createBackdrop();createAsteroids();createNebulae();
  let frameCount=0,total=0;
  app.on('update',dt=>{if(disposed)return;frame.bloom.intensity=mode==='surface'?.10:.34;frame.update();const delta=Math.min(dt,.05);if(!paused)elapsed+=dt;
   if(mode==='flight'&&transition===undefined){travel+=(desiredTravel-travel)*(1-Math.exp(-delta*4));const pose=flightPose(travel);desiredTarget=position(pose.target);const offset=position(pose.position).sub(desiredTarget);const c=Math.cos(flightYaw),s=Math.sin(flightYaw);desiredPosition=new pc.Vec3(desiredTarget.x+offset.x*c+offset.z*s,desiredTarget.y+offset.y,desiredTarget.z+offset.z*c-offset.x*s);}
   const speed=transition===0?1:1-Math.exp(-delta*(transition?5/transition:8));const pos=camera.getPosition().clone().lerp(camera.getPosition(),desiredPosition,speed);target.lerp(target,desiredTarget,speed);if(transition!==undefined&&pos.distance(desiredPosition)<.04&&target.distance(desiredTarget)<.04){transition=undefined;if(mode==='surface'&&coast?.enabled&&!landed){landed=true;callbacks.landed(true);}}
   if(mode!=='flight'){const offset=pos.clone().sub(target),angle=yaw;const x=offset.x*Math.cos(angle)+offset.z*Math.sin(angle),z=offset.z*Math.cos(angle)-offset.x*Math.sin(angle);pos.set(target.x+x,target.y+offset.y+pitch,target.z+z);if(yaw||pitch)desiredPosition.copy(pos);if(!yaw&&!pitch&&pos.distance(desiredPosition)<.001&&target.distance(desiredTarget)<.001){pos.copy(desiredPosition);target.copy(desiredTarget);}}camera.setPosition(pos);camera.lookAt(target);yaw=pitch=0;
   fog?.update(elapsed);energy?.update(elapsed);mirror?.update(mode);if(station)station.enabled=mode!=='surface';
   for(const mist of mists){if(mist.haze){const h=mist.haze,t=elapsed*h.form.speed,distance=camera.getPosition().distance(h.center)/h.radius,smooth=(a,b,x)=>{const v=Math.max(0,Math.min(1,(x-a)/(b-a)));return v*v*(3-2*v);},visibility=1-smooth(30,44,distance),lod=h.index%3===0?1:1-smooth(5,11,distance);mist.entity.enabled=mode!=='surface'&&visibility*lod>.001;if(!mist.entity.enabled)continue;const q=new pc.Quat().setFromEulerAngles(h.form.tilt*180/Math.PI,(Math.sin(t*.018+h.phase)*.10+(h.form.name==='inclined-nebula-ring'?.55:0))*180/Math.PI,(Math.sin(t*.014+h.phase)*.065+(h.form.name==='inclined-nebula-ring'?.22:0))*180/Math.PI),at=q.transformVector(h.base.clone().mulScalar(1+Math.sin(t*.09+h.index*1.7+h.phase)*.035));mist.entity.setPosition(at.add(h.center));mist.material.setParameter('opacity',h.opacity*(.88+.12*Math.sin(t*.12+h.index+h.phase))*visibility*lod*h.form.density);}if(mist.base){const at=mist.base.clone();at.y+=Math.sin(elapsed*.14+mist.index)*.32;mist.entity.setPosition(at);}if(mist.coil){mist.entity.setPosition(serpentSpiralPose(mist.coil.u,Math.sin(elapsed*.12+mist.coil.sectionIndex)*.32).position);}mist.entity.lookAt(camera.getPosition());mist.material.setParameter('time',elapsed);if(mist.flash){const pulse=paused?0:mist.schedule.sample(elapsed).pulse;mist.material.setParameter('flash',pulse);mist.material.setParameter('opacity',pulse);mist.entity.enabled=pulse>.005;}}
   for(const item of labels){const point=item.entity.getPosition().clone();point.y+=item.offset;const screen=camera.camera.worldToScreen(point);const front=point.clone().sub(camera.getPosition()).dot(camera.forward)>0;item.button.hidden=!item.entity.enabled||mode==='surface'||!front||screen.x<20||screen.x>host.clientWidth-20||screen.y<80||screen.y>host.clientHeight-80;item.button.style.transform=`translate(${screen.x}px,${screen.y}px) translate(-50%,0)`;}
   frameCount++;total+=dt;if(total>1){stats.fps=Math.round(frameCount/total);frameCount=0;total=0;host.dataset.fps=String(stats.fps);}stats.calls=app.stats.drawCalls.total;stats.surface=landed;host.dataset.cameraPosition=[pos.x,pos.y,pos.z].map(n=>n.toFixed(2)).join(',');host.dataset.flight=travel.toFixed(3);
   const current=document.getElementById('flight-world');if(current)current.textContent=mode==='observatory'?'Обсерватория':mode==='surface'?'На поверхности':mode==='map'?'Вся галактика':flightWorld(travel);
  });host.dataset.planetTextures='loading';const previews=preloadPlanetPreviews(worlds,loadPlanet);app.start();const results=await previews;if(disposed)return;host.dataset.planetTextures=results.every(r=>r.ok)?'ready':'partial';host.dataset.failedPlanetTextures=results.filter(r=>!r.ok).map(r=>r.id).join(',');if(!results.some(r=>r.ok))throw new Error('No planet textures loaded');queueOriginFull(worlds.find(w=>w.id==='origin'));void loadObservatory();host.dataset.sceneReady='true';
 })().catch(error=>{if(!disposed){console.error('PlayCanvas initialization failed',error);callbacks.failed();}throw error;});
 async function loadPlanet(w){if(w.pending)return w.pending;w.entity.enabled=false;return w.pending=(async()=>{try{const a=await load(w.id,'texture',`/universe/${WORLD_THEMES[w.id].asset}.webp`);w.material.diffuseMap=a.resource;w.material.update();w.loaded=true;w.entity.enabled=true;if(w.id==='origin')host.dataset.originTexture=`${a.resource.width}x${a.resource.height}`;}catch(error){if(!disposed){w.material.diffuse=rgb({origin:0x343c47,aurora:0x164d34,velir:0x183b63,nereya:0x533b25,solis:0x482345}[w.id]);w.material.update();w.entity.enabled=true;console.error('Planet texture failed: '+w.id,error);}w.pending=null;throw error;}})();}
 function queueOriginFull(w){if(!w)return;host.dataset.originFullStatus='queued';const timer=setTimeout(()=>{if(disposed)return;const size=Math.min(8192,device.maxTextureSize);void load('origin full','texture','/universe/origin-moon-v1-8192.jpg').then(full=>{w.material.diffuse=pc.Color.WHITE;w.material.diffuseMap=full.resource;w.material.update();w.loaded=true;w.entity.enabled=true;host.dataset.originFullStatus='uploaded-'+full.resource.width;host.dataset.originTexture=`${full.resource.width}x${full.resource.height}`;}).catch(error=>{host.dataset.originFullStatus='failed';console.error(error);});},1500);cleanup.push(()=>clearTimeout(timer));}
 function createBackdrop(){let seed=8714;const random=()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/4294967296);const points=[],indices=[];for(let i=0;i<2400;i++){const x=(random()-.5)*400,y=(random()-.5)*200,z=-40-random()*320,s=.025+random()*.08,n=points.length/3;points.push(x-s,y-s,z,x+s,y-s,z,x,y+s,z);indices.push(n,n+1,n+2);}const geometry=new pc.Mesh(device);geometry.setPositions(points);geometry.setIndices(indices);geometry.update();const mat=new pc.ShaderMaterial({uniqueName:'astra-stars-unlit',attributes:{aPosition:pc.SEMANTIC_POSITION},vertexGLSL:'attribute vec3 aPosition;uniform mat4 matrix_model;uniform mat4 matrix_viewProjection;void main(){gl_Position=matrix_viewProjection*matrix_model*vec4(aPosition,1.);}',fragmentGLSL:'void main(){gl_FragColor=vec4(.65,.83,1.,1.);}'});const e=new pc.Entity('stars');e.addComponent('render',{meshInstances:[new pc.MeshInstance(geometry,mat)]});app.root.addChild(e);}
 function createAsteroids(){let seed=72319;const rnd=()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/4294967296);const mat=material(0x343640,.03,.02),shared=pc.Mesh.fromGeometry(device,new pc.SphereGeometry({radius:1,latitudeBands:5,longitudeBands:7})),count=host.clientWidth<700?300:700,data=new Float32Array(count*16),transform=new pc.Mat4(),rotation=new pc.Quat();for(let i=0;i<count;i++){const t=(i+rnd()*.8)/count,at=asteroidPoint(t),spread=.35+Math.sin(t*Math.PI)**2*1.3;at.add(new pc.Vec3((rnd()-.5)*spread*2,(rnd()-.5)*spread*1.6,(rnd()-.5)*spread));const size=.055+Math.pow(rnd(),2.7)*.5,scale=new pc.Vec3(size*(.6+rnd()),size*(.6+rnd()*.8),size*(.65+rnd()*.7));rotation.setFromEulerAngles(rnd()*6.28*180/Math.PI,rnd()*6.28*180/Math.PI,rnd()*6.28*180/Math.PI);rnd();transform.setTRS(at,rotation,scale);data.set(transform.data,i*16);}const buffer=new pc.VertexBuffer(device,pc.VertexFormat.getDefaultInstancingFormat(device),count,{data:data.buffer}),instance=new pc.MeshInstance(shared,mat);instance.setInstancing(buffer);cleanup.push(()=>buffer.destroy());const entity=new pc.Entity('asteroid stream');entity.addComponent('render',{meshInstances:[instance]});app.root.addChild(entity);host.dataset.asteroidInstances=String(count);}
 on(canvas,'wheel',e=>{if(e.ctrlKey||e.metaKey)return;e.preventDefault();if(mode==='flight')scrub(desiredTravel+Math.max(-180,Math.min(180,e.deltaY))*.00032);else{zoom(e.deltaY<0?1:-1);yaw+=e.deltaX*.002;}},{passive:false});
 on(canvas,'pointerdown',e=>{press={x:e.clientX,y:e.clientY,type:e.pointerType,dragged:false};canvas.setPointerCapture(e.pointerId);});
  on(canvas,'pointermove',e=>{if(!press)return;const dx=e.clientX-press.x,dy=e.clientY-press.y;if(Math.abs(dx)+Math.abs(dy)>4)press.dragged=true;if(mode==='flight'){scrub(desiredTravel-dy*.0011);flightYaw=Math.max(-.82,Math.min(.82,flightYaw+dx*.0035));}else{yaw+=dx*.003;pitch+=dy*.03;}press.x=e.clientX;press.y=e.clientY;});
 on(canvas,'pointerup',e=>{if(press&&!press.dragged&&camera){const r=canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;let selected,best=Infinity;for(const w of worlds){const s=camera.camera.worldToScreen(w.entity.getPosition()),d=Math.hypot(s.x-x,s.y-y);if(d<70&&d<best){best=d;selected=w;}}if(selected)callbacks.pick(selected.id);}press=null;});on(canvas,'pointercancel',()=>press=null);
 on(canvas,'keydown',e=>{if(['ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();scrub(desiredTravel+(e.key==='ArrowDown'?.035:-.035));}});
 on(reduced,'change',()=>pause(reduced.matches));
 function zoom(direction){if(mode==='flight'){scrub(desiredTravel+direction*.035);return;}const offset=desiredPosition.clone().sub(desiredTarget);offset.mulScalar(direction>0?.85:1.18);desiredPosition=desiredTarget.clone().add(offset);transition=0;}
 function pause(value){paused=value;if(transition!==undefined)transition=0;document.body.classList.toggle('motion-paused',value);try{sessionStorage.setItem('astra.motion-paused',String(value));}catch{}}
 function dispose(){disposed=true;cleanup.forEach(fn=>fn());labels.forEach(l=>l.button.remove());mirror?.dispose();frame?.destroy();app?.destroy();canvas.remove();delete document.body.dataset.cameraMode;}
 return {ready,home,overview,present,focus,land,observatory,setProgress(value){stage=value;for(let i=0;i<labels.length;i++)labels[i].button.classList.toggle('unexplored',i>stage);},setMode(value){value==='map'?overview():home(true);},scrub,stats,zoom,pause,get paused(){return paused;},dispose};
}
