import type { ResearchState, ResearchAnswer } from './research.ts';
const esc=(v:string)=>v.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function researchStats(s:ResearchState){
  const answers=s.answers;
  return {days:new Set(answers.map(a=>a.day)).size,questions:answers.filter(a=>a.kind==='question').length,games:answers.filter(a=>a.kind==='game').length,
    completed:answers.filter(a=>a.kind==='trial'&&a.source==='SELF_REPORTED_ACTION'&&a.choices.includes('Сделал')).length,
    partial:answers.filter(a=>a.kind==='trial'&&a.source==='SELF_REPORTED_ACTION'&&a.choices.includes('Попробовал частично')).length,
    skipped:answers.filter(a=>a.choices.includes('Пропустить')).length};
}
export function answerStatus(a:ResearchAnswer){return a.choices.includes('Пропустить')?'Пропущено':a.choices.includes('Перенести')?'Перенесено':a.kind==='trial'?a.choices.includes('Сделал')?'Выполнено':a.choices.includes('Попробовал частично')?'Частично':'Без выполнения':'Ответ сохранён';}
export function researchInfographic(s:ResearchState){const n=researchStats(s);return `<section class="research-infographic" aria-label="Журнал исследования"><div><strong>${n.days}</strong><span>дней с записями</span></div><div><strong>${n.questions+n.games}</strong><span>вопросов и игр</span></div><div><strong>${n.completed}</strong><span>выполненных проб</span></div></section><p class="small-note">Частичных проб: ${n.partial}. Пропущенных шагов: ${n.skipped}. Ответы и игры учитываются отдельно от выполненных действий.</p>`;}
export function journalBody(s:ResearchState,today:string){return `${researchInfographic(s)}<p>Отметки и наблюдения по дням. Исправление сохраняет предыдущую версию.</p><div class="journal-table-wrap"><table class="journal-table journal-days"><caption>Твой журнал</caption><thead><tr><th scope="col">Дата</th><th scope="col">Шаг</th><th scope="col">Статус</th></tr></thead><tbody>${[...s.answers].sort((a,b)=>b.day.localeCompare(a.day)).map(a=>`<tr><td>${a.day}</td><td><strong>${a.kind==='trial'?'Проба':a.kind==='game'?'Игра':'Вопрос'}</strong><details><summary>Ответ и наблюдение</summary><p>${esc(a.prompt)}</p><p>${esc(a.choices.join(' · '))}</p><p>${esc(a.note)}</p><a href="#research/${a.day}">Исправить · версия ${a.revision}</a></details></td><td>${answerStatus(a)}</td></tr>`).join('')||'<tr><td colspan="3">Первый ответ появится здесь после сохранения.</td></tr>'}</tbody></table></div>${s.answers.some(a=>a.day===today)?'<a class="primary wide" href="#today">Сегодняшний итог</a>':'<a class="primary wide" href="#research">Сделать сегодняшний шаг</a>'}`;}
