import { monthReview,monthReady } from './month-review';
import { viewKey,useObservatory,observatoryToday,observationAtlas } from './observatory';
import './observatory.css';
import { natalBody } from './natal-ui';
import { researchInfographic,journalBody } from './research-dashboard';
import { blankBirth,blankWishes,blankRhythm,newResearch,nextResearchRoute,validateBirth,commitProfile,previousMonthWeeks,commitMemories,researchCard,saveResearchAnswer,canRevealFocus } from './research';
import type { Birth,Wishes,Rhythm,ResearchState } from './research';
import type { Journey } from './journey';

const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const button=(action:string,text:string,primary=false)=>`<button type="button" class="${primary?'primary wide':'text-button'}" data-research="${action}">${text}</button>`;
const input=(name:string,label:string,value:unknown,type='text',extra='')=>`<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;
const area=(name:string,label:string,value:unknown,max=500)=>`<label>${label}<textarea name="${name}" maxlength="${max}">${esc(value)}</textarea></label>`;
const field=(label:string,value:unknown)=>`<div class="research-fact"><small>${label}</small><p>${esc(value||'Пока не указано')}</p></div>`;
const options=(values:readonly string[],selected:unknown)=>values.map(v=>`<option ${v===selected?'selected':''}>${esc(v)}</option>`).join('');
const sourceNames={USER_STATEMENT:'Со слов пользователя',TASK_RESPONSE:'Ответ в конкретной игре',SELF_REPORTED_ACTION:'Выполнение со слов пользователя'};
type Host={state:()=>ResearchState|undefined;set:(s:ResearchState)=>void;today:()=>string;journey:()=>Journey;go:(route:string)=>void;panel:(title:string,kicker:string,body:string)=>void;save:()=>void;storage:()=>string;allowed:()=>boolean;toast:(text:string)=>void};

export function createResearchUI(h:Host){
  let observatory=true;try{observatory=useObservatory(localStorage.getItem(viewKey));}catch{/* The view remains switchable without storage. */}
  let current='today',opened=false,internalNavigation=false,editingDay='';const positions=new Map<string,number>();
  const s=()=>h.state()??newResearch();
  const write=(value:ResearchState)=>{h.set(value);h.save();};
  const draft=(key:string,fallback:object)=>({...fallback,...s().drafts[key]});
  const now=()=>new Date().toISOString();
  const go=(r:string)=>h.go(r);
  const main=(title:string,kicker:string,body:string,back='today')=>{
    document.body.classList.toggle('observatory-ui',observatory);
    if(observatory&&current==='today'){title=s().complete?'Тихая обсерватория':'Сначала познакомимся';body=observatoryToday(s(),h.today());}
    if(observatory&&current==='results'){title='Атлас наблюдений';body=observationAtlas(s())+`<details><summary>Подробный обзор и история</summary>${body}</details>`;}
    const controls=`<div class="observatory-tools"><button type="button" class="text-button" data-action="motion" data-reading-motion aria-pressed="${document.body.classList.contains('motion-paused')}">${document.body.classList.contains('motion-paused')?'Включить движение':'Спокойный режим'}</button>${button('interface-toggle',observatory?'Вернуть прежний вид':'Включить новый вид')}${current!=='today'?button('back:'+back,'← Назад'):''}</div>`;
    h.panel(title,kicker,controls+body);
    if(observatory){const panel=document.getElementById('panel');if(panel){panel.dataset.presentation='content';panel.dataset.reading='true';}}
  };
  function storageText(){return h.journey().demo?'Демо отдельно от твоих данных. После выхода оно не сохраняется.':h.storage()==='error'?'Не удалось сохранить на устройстве. Ответы остаются в этой вкладке. Повтори сохранение в профиле.':h.allowed()&&h.storage()==='saved'?'Сохранено на этом устройстве.':'Ответы пока только в этой вкладке. Сохранение после закрытия можно включить в профиле.';}
  const step=(n:number)=>`<p class="research-step">Знакомство · шаг ${n} из 4</p>`;
  const birthSummary=(b:Birth)=>field('Дата рождения',b.date)+field('Время рождения',b.accuracy==='unknown'?'Неизвестно — не подставляем условное время':`${b.time}${b.until?'–'+b.until:''} · ${b.accuracy==='exact'?'точное':'приблизительное'}`)+field('Место рождения',b.place);
  function welcome(){main('Сначала познакомимся','ИСТОК / НАЧАЛО',`<p class="lead">У тебя есть мечты, но пока нет понятного пути?</p><p>Расскажи о желаниях и обстоятельствах. Около месяца будем знакомиться через вопросы, игры, наблюдения и добровольные пробы. Затем обсудим варианты и соберём твою персональную инструкцию.</p><ol class="research-path"><li>Расскажешь о себе</li><li>Исследуешь интересы в своём темпе</li><li>Выберешь, к чему двигаться</li></ol>${button('begin','Начать знакомство ↗',true)}${button('go:example','Посмотреть пример результата')}`,'galaxy');}
  function birth(){const b=draft('birth',s().birth??blankBirth) as Birth;main('Данные для твоей натальной карты','ЗНАКОМСТВО / ДАННЫЕ РОЖДЕНИЯ',`${step(1)}<p>Дата и место обязательны. Если время неизвестно, укажи это явно — мы не будем его угадывать.</p><form id="research-birth" data-research-form="birth">${input('date','Дата рождения',b.date,'date','required')}
    <label>Точность времени<select name="accuracy"><option value="unknown" ${b.accuracy==='unknown'?'selected':''}>Не знаю</option><option value="exact" ${b.accuracy==='exact'?'selected':''}>Точное</option><option value="approximate" ${b.accuracy==='approximate'?'selected':''}>Приблизительное</option></select></label>
    <div data-birth-time ${b.accuracy==='unknown'?'hidden':''}>${input('time','Время рождения',b.time,'time')}</div><div data-birth-until ${b.accuracy!=='approximate'?'hidden':''}>${input('until','Конец приблизительного интервала — необязательно',b.until,'time')}</div>
    ${input('place','Место рождения: город, регион, страна',b.place,'text','list="birth-cities" maxlength="200" required autocomplete="off"')}<datalist id="birth-cities"><option value="Москва, Москва, Россия"></option><option value="Санкт-Петербург, Санкт-Петербург, Россия"></option><option value="Казань, Республика Татарстан, Россия"></option><option value="Алматы, Алматы, Казахстан"></option></datalist><p class="small-note">Выбери город из подсказок или введи его полностью. Если время неизвестно, карта сохранит это ограничение.</p><details><summary>Уточнение точности</summary>${area('note','Откуда известно время — необязательно',b.note)}</details><button class="primary wide" type="submit">Проверить данные</button></form>`,s().complete?'profile':'welcome');}
  function birthReview(){const b=validateBirth(draft('birth',s().birth??blankBirth) as Birth,h.today());main('Всё указано верно?','ДАННЫЕ РОЖДЕНИЯ / ПРОВЕРКА',`${birthSummary(b)}<p class="small-note">Место рождения не заменяется текущим местоположением. Часовой пояс уведомлений — отдельная настройка.</p>${button('confirm-birth','Подтвердить данные',true)}${button('go:birth','Исправить')}`,'birth');}
  function wishes(){const w=draft('wishes',s().wishes??blankWishes) as Wishes;main('Чего тебе сейчас хочется?','ЗНАКОМСТВО / МОИ ЖЕЛАНИЯ',`${step(2)}<p class="lead">Выбери близкие желания или добавь свои. Можно несколько.</p><div class="wish-options">${['Найти новое направление','Освоить новый навык','Начать свой проект','Больше путешествовать','Вернуть спокойный ритм','Пока не знаю'].map(v=>`<button type="button" data-research="wish:${v}" aria-pressed="${w.original.split('\n').includes(v)}">${v}</button>`).join('')}</div><form id="research-wishes" data-research-form="wishes">${area('original','Мои желания — своими словами',w.original,2000)}<p class="small-note">Например: своё дело, музыка, путешествия или больше свободного времени. Это подсказки, не готовые цели.</p><details><summary>Что важно сохранить и чего не хочется?</summary>${area('preserve','Хочу сохранить',w.preserve,2000)}${area('avoid','Точно не хочу',w.avoid,2000)}</details><button class="primary wide" type="submit">Проверить формулировки</button></form>`,'birth');}
  function wishesReview(){const w=draft('wishes',s().wishes??blankWishes) as Wishes;main('Это твои желания?','МОИ ЖЕЛАНИЯ / ПРОВЕРКА',`<p>Твои слова сохранены без автоматических выводов. Можно разделить желания по строкам и уточнить формулировки.</p><form id="research-wishes-review" data-research-form="wishes"><details><summary>Исходный текст</summary><p>${esc(w.original)}</p></details>${area('confirmed','Желания, которые я подтверждаю',w.confirmed||w.original,2000)}<p class="small-note">Ни одно желание не назначается главной целью: порядок определишь ты после наблюдений и проб.</p><button class="primary wide" type="submit">Подтвердить желания</button></form>`,'wishes');}
  function rhythm(){const r=draft('rhythm',s().rhythm??blankRhythm) as Rhythm;main('Твой ритм и возможности','ЗНАКОМСТВО / РЕАЛЬНЫЕ УСЛОВИЯ',`${step(3)}<p>Начнём с главного. Это твои условия, а не расписание, которое мы уже назначили.</p><form id="research-rhythm" data-research-form="rhythm"><label>Как устроен график?<select name="kind"><option value="unknown" ${r.kind==='unknown'?'selected':''}>Пока не знаю</option><option value="fixed" ${r.kind==='fixed'?'selected':''}>Обычно предсказуемый</option><option value="shifts" ${r.kind==='shifts'?'selected':''}>Плавающий / сменный</option></select></label>${area('windows','Сколько времени реально готов выделять?',r.windows,2000)}${area('resources','Навыки, опыт и доступные инструменты — необязательно',r.resources,2000)}${area('limits','Обязательства и ограничения — необязательно',r.limits,2000)}<button class="primary wide" type="submit">Проверить знакомство</button></form>`,'wishes');}
  function review(){const st=s();if(!st.wishes||!st.rhythm){go(nextResearchRoute(st));return;}main('Вот с чем мы начинаем','ЗНАКОМСТВО / ТВОИ СЛОВА',`${step(4)}${field('Ты рассказал о желаниях',st.wishes.confirmed)}${field('Хочешь сохранить',st.wishes.preserve)}${field('Не хочешь',st.wishes.avoid)}${field('Твоё реальное время',st.rhythm.windows)}${field('График',st.rhythm.kind==='shifts'?'Плавающий':st.rhythm.kind==='fixed'?'Предсказуемый':'Пока неизвестен')}<details><summary>Исходные данные и возможности</summary>${st.birth?birthSummary(st.birth):'<p>Данные рождения отложены.</p>'}${field('Навыки — с твоих слов',st.rhythm.resources)}${field('Ограничения',st.rhythm.limits)}</details><p>Дальше будем уточнять, что привлекает в желаниях и какие условия подходят. Готового жизненного маршрута ещё нет.</p>${button('finish-intro','Перейти к первому исследованию',true)}${button('go:wishes','Исправить желания')}${button('go:rhythm','Исправить условия')}`,'rhythm');}
  function today(){const st=s(),row=st.answers.find(a=>a.day===h.today());
    if(!st.complete){main(st.step?'Продолжим<br>знакомство':'Начнём<br>знакомство','СЕГОДНЯ / НАЧАЛО',`<div class="invitation-time"><svg viewBox="0 0 28 28" aria-hidden="true"><circle cx="14" cy="14" r="12"/><path d="M14 6v9h7"/></svg>Около 5 минут</div><p class="invitation-copy">${st.step?'Продолжим с того места, где остановились.':'Расскажи о себе и желаниях — с этого начинается твой путь.'}</p><button type="button" class="primary invitation-action" data-research="go:${nextResearchRoute(st)}">${st.step?'Продолжить':'Начать'} <span aria-hidden="true">→</span></button>`);return;}
    if(!st.memoryDone){main('Вспомним прошлый месяц','СЕГОДНЯ / ПЕРВОЕ ИССЛЕДОВАНИЕ',`<div class="research-main-card"><span class="research-duration">3–5 минут · необязательно</span><p class="lead">Отметь события, которые хорошо помнишь. Можно ответить «Не помню» или пропустить.</p>${button('go:memories','Начать',true)}</div><p>Воспоминания сохраняются отдельно от фокуса дня и не заменяют записи о реальных действиях.</p>${button('skip-memories','Не хочу вспоминать сейчас')}`);return;}
    if(monthReady(st,h.today())){main('Твои записи сохранены','СЕГОДНЯ / ОБЗОР И ПРОДОЛЖЕНИЕ',`<p class="lead">Можно посмотреть накопленные наблюдения или продолжить исследование в своём темпе. Догонять пропущенные дни не нужно.</p>${researchInfographic(st)}<p>Обзор доступен, но сам срок в 30 дней не означает, что данных достаточно для вывода.</p><a class="primary wide" href="#results">Открыть обзор месяца</a><a class="text-button" href="#journal">Мои записи по дням</a>${button('go:research',row?'Исправить сегодняшний ответ':'Перейти к сегодняшнему вопросу')}`);return;}
    if(row){main('На сегодня всё','СЕГОДНЯ / ИССЛЕДОВАНИЕ ЗАВЕРШЕНО',`<div class="research-main-card"><p class="lead">Ответ принят. Сегодня не нужно выполнять ещё десять заданий.</p>${field('Твой ответ',row.choices.join(' · '))}<p>Продолжим в другой день. Пропуск и смена мнения не обнуляют путь.</p>${button('go:results','Посмотреть наблюдения',true)}</div>${button('go:research','Исправить сегодняшний ответ')}`);return;}
    const card=researchCard(st,h.today());main('Продолжим знакомство','СЕГОДНЯ / ИССЛЕДОВАНИЕ',`<div class="research-main-card"><span class="research-duration">${card.kind==='trial'?'До 5 минут · добровольно':'1–3 минуты'}</span><h3>${esc(card.title)}</h3><p>${esc(card.prompt)}</p>${button('go:research',Object.keys(st.drafts.research??{}).length?'Продолжить':'Начать исследование',true)}</div><p class="small-note">Один ответ уточняет опыт, но не определяет твою личность.</p>`);
  }
  function memories(){const rows=previousMonthWeeks(h.today()),d=draft('memories',{}) as Record<string,string>;main('Восстанови свой месяц','ИССЛЕДОВАНИЕ / ВОСПОМИНАНИЯ',`<p>Какие события ты можешь назвать? Работа, общение, занятия или изменения планов — без предположений о том, что должно было случиться.</p><form id="research-memories" data-research-form="memories">${rows.map(r=>`<fieldset><legend>${r.from} — ${r.to}</legend>${area('note'+r.week,'Что запомнилось?',d['note'+r.week]??s().memories[r.week]?.note??'')}<label>Точность воспоминаний<select name="certainty${r.week}">${options(['Не помню','Помню уверенно','Примерно','Ничего заметного'],d['certainty'+r.week]??s().memories[r.week]?.certainty??'Не помню')}</select></label></fieldset>`).join('')}<button class="primary wide" type="submit">Сохранить воспоминания</button></form>${button('skip-memories','Пропустить восстановление')}`);}
  function research(){const st=s();if(!st.complete){go(nextResearchRoute(st));return;}if(!st.memoryDone){go('memories');return;}const card=researchCard(st,h.today()),old=st.answers.find(a=>a.day===h.today()),d=draft('research',{choice:old?.choices??[],note:old?.note??''}) as {choice:string[]|string;note:string};const chosen=Array.isArray(d.choice)?d.choice:[d.choice];
    if(card.kind==='game'&&d.note===undefined)d.note='';
    main(card.title,`ИССЛЕДОВАНИЕ / ${card.kind==='game'?'ИГРА НА ВЫБОР':card.kind==='trial'?'ДОБРОВОЛЬНАЯ ПРОБА':'ВОПРОС'}`,`<p class="lead">${esc(card.prompt)}</p><p>${esc(card.hint)}</p>${card.kind==='trial'&&st.trialAccepted!==h.today()?`<div class="research-main-card">${button('accept-trial','Хочу попробовать',true)}<p>После пробы вернись и расскажи, как прошло.</p></div>`:''}<form id="research-answer" data-research-form="research"><fieldset><legend>${card.kind==='game'?'Выбери до двух вариантов':'Твой ответ'}</legend><div class="research-choices">${card.choices.filter(c=>card.kind!=='trial'||st.trialAccepted===h.today()||!['Сделал','Попробовал частично'].includes(c)).map(c=>`<label><input type="${card.kind==='game'?'checkbox':'radio'}" name="choice" value="${esc(c)}" ${chosen.includes(c)?'checked':''}><span>${esc(c)}</span></label>`).join('')}</div></fieldset>${area('note','Моё дополнение — необязательно',d.note)}<button class="${card.kind==='trial'&&st.trialAccepted!==h.today()?'ghost':'primary'} wide" type="submit">Подтвердить ответ</button></form>`);
  }
  function astrology(mode='astrology'){const st=s();let content='';
    if(mode==='forecast')content=`<p class="small-note">Сейчас здесь общая символическая подсказка, а не персональный прогноз по карте рождения.</p>${canRevealFocus(st,h.today())?`<div class="astro-focus"><small>СИМВОЛИЧЕСКИЙ ФОКУС</small><h3>Заметь, что сегодня возвращает тебе энергию</h3><p>Наблюдай без попытки подогнать события: какой выбор даёт ясность, а какой создаёт лишнее напряжение?</p></div>`:`<div class="research-main-card"><h3>Сначала — твои наблюдения</h3><p>Ты выбрал показ после ответа. Сначала запиши, как прошёл день, без подсказки. Можно ответить «Не помню» или пропустить вопрос.</p>${button('go:research','К сегодняшнему вопросу',true)}</div>`}<form id="research-forecast"><p>Как показать фокус?</p><div class="research-choices"><label><input type="radio" name="mode" value="open" ${st.forecastMode==='open'?'checked':''}><span>Открывать до исследования</span></label><label><input type="radio" name="mode" value="blind" ${st.forecastMode==='blind'?'checked':''}><span>Открывать после ответов о дне</span></label></div><p class="small-note">Это символическая подсказка для самонаблюдения, а не предсказание. Она не меняет задания и не назначает цели. Раннее раскрытие может влиять на последующие ответы; смена режима не делает уже увиденную подсказку неизвестной.</p><button class="primary wide" type="submit">Сохранить режим</button></form>`;
    else if(mode==='astro-checks')content=`<div class="research-main-card"><h3>Сопоставлений пока нет</h3><p>Персональные прогнозы и сохранение их проверок ещё не подключены. Поэтому здесь нет показателя совпадений.</p></div><p class="small-note">Ответы на обычные вопросы и общая символическая подсказка не считаются астрологической проверкой.</p>`;
    else content=natalBody(st,h.today());
    main(mode==='forecast'?'Прогноз':mode==='astro-checks'?'История проверок':'Астрология','КАРТА / ТРАКТОВКИ / ПРОВЕРКИ',`<nav class="research-tabs" aria-label="Разделы астрологии">${button('go:astrology','Моя карта')}${button('go:forecast','Прогноз')}${button('go:astro-checks','Проверки')}</nav>${content}<details><summary>Как разделяются сведения</summary><p>Расчёт положений, традиционная трактовка и твой ответ — разные источники. Астрологическая интерпретация не доказывает характер, способности или будущие события.</p></details>`);
  }
  function results(){const st=s(),days=new Set(st.answers.map(a=>a.day)).size;main(monthReady(st,h.today())?'Твой первый месяц':'Твои наблюдения','РЕЗУЛЬТАТЫ / ОПЫТ И ОТКРЫТЫЕ ВОПРОСЫ',`<nav class="result-nav" aria-label="Навигация по результатам"><a href="#journal">Журнал по дням</a><a href="#plan">Следующий план</a><a href="#astrology">Натальная карта</a></nav>${researchInfographic(st)}${monthReview(st,h.today())}<a class="text-button" href="#journal">Открыть журнал по дням →</a>${!st.answers.length?'<p class="lead">Здесь будут появляться твои наблюдения и результаты.</p><p>Готовых выводов о тебе ещё нет.</p>':`<p class="lead">Есть ответы за ${days} ${days===1?'день':'дней'}. Это материал для знакомства, не оценка личности.</p>`}${st.wishes?field('Желания, которые ты подтвердил',st.wishes.confirmed):''}${st.answers.length&&!monthReady(st,h.today())?`<div class="research-main-card"><h3>Промежуточный обзор</h3><p>Вопросов: ${st.answers.filter(a=>a.kind==='question').length}; игровых ответов: ${st.answers.filter(a=>a.kind==='game').length}; отметок о пробах со слов пользователя: ${st.answers.filter(a=>a.source==='SELF_REPORTED_ACTION').length}.</p><p>Предпочтение в игре и выполнение пробы не одно и то же. Для устойчивых выводов пока недостаточно материала.</p></div>`:''}<details><summary>На чём основано? Ответы и ограничения</summary>${st.answers.map(a=>`<article class="research-evidence"><small>${a.day} · ${sourceNames[a.source]} · версия ${a.revision}</small><h3>${esc(a.prompt)}</h3><p>${esc(a.choices.join(' · '))}</p>${a.note?`<p>${esc(a.note)}</p>`:''}${a.day===h.today()?button('go:research','Исправить ответ'):''}</article>`).join('')||'<p>Ответов пока нет.</p>'}${st.memories.length?`<h3>Воспоминания — отдельно</h3>${st.memories.map(r=>field(`${r.from} — ${r.to} · ${r.certainty}`,r.note)).join('')}${button('go:memories','Исправить воспоминания')}`:''}<p>Предыдущих версий ответов: ${st.history.length}. Самоотчёты и символический астрологический слой всегда показаны отдельно.</p></details><details><summary>Как собирается персональная инструкция?</summary><p>По мере накопления материала ASTRA сопоставит подтверждённые желания, реальные ограничения, ответы и добровольные пробы.</p><p>Перед сохранением маршрута ты увидишь варианты и сам выберешь направление. Старые планы не подменяют новое исследование.</p>${button('go:example','Посмотреть структуру на примере')}</details>${button('go:today','Вернуться к сегодняшнему шагу',true)}${h.journey().data.observations.length||h.journey().data.approvedPlan?'<details><summary>Предыдущие записи</summary><p>Они сохранены в истории и входят в экспорт, но не считаются итогом нового знакомства.</p><button class="text-button" data-action="export">Скачать все данные</button></details>':''}`);}
  function profile(){const st=s();main('Профиль','МОИ СВЕДЕНИЯ / НАСТРОЙКИ',`${st.birth?birthSummary(st.birth):''}${st.wishes?field('Мои желания',st.wishes.confirmed):''}${st.rhythm?field('Моё время',st.rhythm.windows)+field('Мои ресурсы',st.rhythm.resources)+field('Ограничения',st.rhythm.limits):''}<div class="research-settings">${button('go:wishes','Мои желания →')}${button('go:rhythm','График и возможности →')}${button('go:birth','Данные рождения →')}${button('go:review','Сводка знакомства →')}</div><details open><summary>Мой прогресс</summary><p>${storageText()}</p>${h.journey().demo?'<p>Демо идёт отдельно и не меняет обычный профиль.</p>':`<button class="${h.allowed()?'ghost':'primary'} wide" data-action="allow-storage">${h.allowed()?'Повторить сохранение':'Включить сохранение'}</button>${h.allowed()?'<button class="text-button" data-action="forget-storage">Удалить сохранённую копию</button>':''}`}<button class="text-button" data-action="export">Скачать резервную копию</button></details><details><summary>Перенос данных</summary><p>Резервная копия включает ответы, историю исправлений и выбранный маршрут.</p></details><details><summary>Помощь</summary><p>Сначала знакомство, затем короткие исследования. Ответы можно пропускать; готовая профессия не назначается.</p>${button('go:welcome','Как работает ASTRA')}</details>${st.complete?button('go:today','Продолжить исследование',true):button('go:'+nextResearchRoute(st),'Продолжить знакомство',true)}`);}
  function example(){main('Как выглядит результат','ПРИМЕР / НЕ ТВОИ ДАННЫЕ',`<p class="demo-note">Вымышленный образец структуры. Не персональная рекомендация.</p><p class="lead">«Хочу своё дело, люблю музыку, хочу путешествовать. Увольняться не готов».</p><ol class="research-path"><li><strong>Желания и приоритеты</strong><p>Музыку оставить хобби, идею дохода проверять отдельно — только если так решил сам человек.</p></li><li><strong>Варианты</strong><p>Сравнить небольшой собственный проект и развитие навыка. Для каждого: время, ресурсы, ограничения и неизвестное.</p></li><li><strong>Ближайший шаг</strong><p>Согласованная бесплатная проверка выбранной гипотезы; не обещание дохода.</p></li><li><strong>Дальнейшие этапы</strong><p>Подробная ближайшая неделя и гибкие точки пересмотра на 30 / 60 / 90 дней.</p></li><li><strong>Основания и астрология</strong><p>Ответы и пробы с датами; отдельно трактовки, совпадения и расхождения. Недостающие данные названы.</p></li></ol>${button('go:today','К своему знакомству',true)}`,'welcome');}
  const aliases:Record<string,string>={'planet/origin':'profile','planet/aurora':'today','planet/velir':'journal','planet/nereya':'plan','planet/solis':'results',route:'journal',discoveries:'journal',plans:'plan',context:'wishes',companion:'today'};
  function editAnswer(){
    const st=s(),row=st.answers.find(a=>a.day===editingDay);if(!row){go('results');return;}
    const saved=st.drafts.researchEdit,d=saved?.day===editingDay?saved:{choice:row.choices,note:row.note};
    const selected=Array.isArray(d.choice)?d.choice:[d.choice];
    main('Уточнить ответ','РЕЗУЛЬТАТЫ / ИСПРАВЛЕНИЕ',`<p>${row.day} · предыдущая версия останется в истории.</p><p class="lead">${esc(row.prompt)}</p><form id="research-edit-answer" data-research-form="researchEdit"><input type="hidden" name="day" value="${row.day}"><div class="research-choices">${(row.options??row.choices).filter(c=>row.kind!=='trial'||row.source==='SELF_REPORTED_ACTION'||!['Сделал','Попробовал частично'].includes(c)).map(c=>`<label><input type="${row.kind==='game'?'checkbox':'radio'}" name="choice" value="${esc(c)}" ${selected.includes(c)?'checked':''}><span>${esc(c)}</span></label>`).join('')}</div>${area('note','Моё дополнение — необязательно',d.note)}<button class="primary wide" type="submit">Сохранить исправление</button></form>`,'results');
  }
  function render(route:string){
    if(/^research\/\d{4}-\d{2}-\d{2}$/.test(route)){editingDay=route.slice(9);current=route;editAnswer();return true;}
    const r=aliases[route]??route;const screens:Record<string,()=>void>={journal:()=>main('Журнал экспедиции','ДАТЫ / ДЕЙСТВИЯ / НАБЛЮДЕНИЯ',journalBody(s(),h.today()),'results'),plan:()=>main('Мой план','РЕЗУЛЬТАТЫ / СЛЕДУЮЩИЙ ПЛАН',`<p class="lead">Персональный план ещё не сформирован.</p><p>Здесь появятся варианты с основаниями, выбором направления и отметками о выполнении. Пока можно проверить свои условия и вернуться к наблюдениям.</p>${s().rhythm?field('Доступное время',s().rhythm!.windows):'<p>Сначала выбери удобный ритм.</p>'}<ol class="research-path"><li>Сегодня: ${s().complete?'короткий вопрос, игра или добровольная проба':'закончить знакомство'}.</li><li>После шага: сохранить ответ и своё наблюдение.</li><li>Следующий визит: продолжить с учётом журнала.</li></ol>${button('go:today','К сегодняшнему шагу',true)}${button('go:rhythm','Изменить ритм')}${button('go:journal','Посмотреть журнал')}`,'today'),welcome,birth,'birth-review':birthReview,wishes,'wishes-review':wishesReview,rhythm,review,today,memories,research,astrology,forecast:()=>astrology('forecast'),'astro-checks':()=>astrology('astro-checks'),results,profile,example};
    if(!screens[r])return false;
    const oldScroll=document.getElementById('panel-scroll');if(oldScroll&&current)positions.set(current,oldScroll.scrollTop);if(opened&&r!==current)internalNavigation=true;opened=true;current=r;
    if(['review','wishes-review','birth-review'].includes(r)&&!s().complete){if(r==='review'&&(!s().wishes||!s().rhythm)){go(nextResearchRoute(s()));return true;}}
    try{screens[r]();}catch{birth();}
    if(r==='results'&&s().answers.length){
      const extra=document.createElement('details');extra.innerHTML='<summary>Исправить записи прошлых дней</summary>'+s().answers.map(a=>button('go:research/'+a.day,`${a.day} · версия ${a.revision}`)).join('');
      document.getElementById('panel-scroll')?.append(extra);
    }
    const panelScroll=document.getElementById('panel-scroll');if(panelScroll)panelScroll.scrollTop=positions.get(r)??0;
    return true;
  }
  function capture(form:HTMLFormElement){const key=form.dataset.researchForm;if(!key)return;const d:Record<string,string|string[]>={...s().drafts[key]},f=new FormData(form);for(const name of new Set([...form.elements].map(el=>(el as HTMLInputElement).name).filter(Boolean)))d[name]=name==='choice'?f.getAll(name).map(String):String(f.get(name)??'');write({...s(),drafts:{...s().drafts,[key]:d}});document.querySelectorAll('[data-save-status]').forEach(el=>el.textContent=storageText());if(key==='birth'){const accuracy=f.get('accuracy');document.querySelector<HTMLElement>('[data-birth-time]')!.hidden=accuracy==='unknown';document.querySelector<HTMLElement>('[data-birth-until]')!.hidden=accuracy!=='approximate';}}
  function submit(form:HTMLFormElement){if(!form.id.startsWith('research-'))return false;capture(form);const f=new FormData(form),st=s();
    switch(form.id){
      case 'research-birth':validateBirth(draft('birth',blankBirth) as Birth,h.today());go('birth-review');break;
      case 'research-wishes':{const w=draft('wishes',blankWishes) as Wishes;if(!w.original.trim())throw new Error('Напиши желания своими словами или «Пока не знаю».');write({...st,drafts:{...st.drafts,wishes:{...w,confirmed:w.original}}});go('wishes-review');break;}
      case 'research-wishes-review':{const w=draft('wishes',blankWishes) as Wishes;if(!w.confirmed.trim())throw new Error('Подтверди формулировку или напиши «Пока не знаю».');write({...commitProfile(st,'wishes',w,now()),step:st.complete?4:3});go(st.complete?'profile':'rhythm');break;}
      case 'research-rhythm':write({...commitProfile(st,'rhythm',draft('rhythm',blankRhythm) as Rhythm,now()),step:4});go('review');break;
      case 'research-memories':write(commitMemories(st,previousMonthWeeks(h.today()).map(r=>({...r,note:String(f.get('note'+r.week)??'').trim(),certainty:String(f.get('certainty'+r.week)),source:'RETROSPECTIVE_USER_STATEMENT'}))));go('today');break;
      case 'research-answer':write(saveResearchAnswer(st,h.today(),f.getAll('choice').map(String),String(f.get('note')??''),now()));go('today');break;
      case 'research-edit-answer':if(!st.answers.some(a=>a.day===editingDay))throw new Error('Этой записи нет.');write(saveResearchAnswer(st,editingDay,f.getAll('choice').map(String),String(f.get('note')??''),now()));go('results');break;
      case 'research-forecast':write({...st,forecastMode:f.get('mode')==='open'?'open':'blind'});h.toast('Режим просмотра сохранён.');render('forecast');break;
    }return true;
  }
  function click(target:HTMLElement){const a=target.dataset.research;if(!a)return false;
    if(a==='interface-toggle'){
      document.querySelectorAll<HTMLFormElement>('form[data-research-form]').forEach(capture);
      observatory=!observatory;try{localStorage.setItem(viewKey,observatory?'observatory':'classic');}catch{h.toast('Вид изменён только в этой вкладке.');}
      positions.clear();render(current);document.querySelector<HTMLElement>('[data-research="interface-toggle"]')?.focus();return true;
    }
    if(a.startsWith('back:')){if(internalNavigation)history.back();else go(a.slice(5));return true;}
    if(a.startsWith('go:')){go(a.slice(3));return true;}const st=s();
    if(a.startsWith('wish:')){const value=a.slice(5),w=draft('wishes',st.wishes??blankWishes) as Wishes,rows=w.original.split('\n').filter(Boolean);w.original=(rows.includes(value)?rows.filter(v=>v!==value):[...rows,value]).join('\n');write({...st,drafts:{...st.drafts,wishes:{...w}}});render('wishes');return true;}
    if(a==='begin'){write({...st,step:st.complete?st.step:1});go('birth');}
    if(a==='confirm-birth'){write({...commitProfile(st,'birth',validateBirth(draft('birth',blankBirth) as Birth,h.today()),now()),birthDeferred:false,step:st.complete?4:2});go(st.complete?'astrology':'wishes');}
    if(a==='finish-intro'){if(!st.wishes||!st.rhythm||(!st.birth&&!st.birthDeferred))throw new Error('Проверь желания, условия и выбор по данным рождения.');write({...st,complete:true,step:4});go('today');}
    if(a==='skip-memories'){write({...st,memoryDone:true});go('today');}
    if(a==='accept-trial'){write({...st,trialAccepted:h.today()});render('research');}
    return true;
  }
  return {render,capture,submit,click,storageText};
}
